---
-- 电视剧
---

CREATE TABLE T_DRAMA (
  ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO T_DRAMA(ID, NAME) VALUES ('1', 'The Big Bang Theory');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('2', 'Masters of Sex');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('3', 'Ballers');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('4', 'Quarry');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('5', 'Better Call Saul');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('6', 'The Walking Dead');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('7', 'Sherlock');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('8', 'Game of Thrones');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('9', 'Black Sails');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('10', 'Criminal Minds');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('11', 'How to Get Away with Murder');
INSERT INTO T_DRAMA(ID, NAME) VALUES ('12', 'Modern Family');
